#!/bin/bash

# ==========================================
# Apply Storage RLS Policies - Quick Fix
# ==========================================

echo ""
echo "🔒 Storage RLS Policies Need to be Applied"
echo "=========================================="
echo ""
echo "⚠️  Error: new row violates row-level security policy"
echo ""
echo "This means the storage buckets exist, but the RLS policies"
echo "that allow uploaders to insert files haven't been applied yet."
echo ""
echo "📋 SOLUTION - Apply RLS Policies Manually:"
echo "=========================================="
echo ""
echo "1. Open Supabase Dashboard SQL Editor:"
echo "   https://supabase.com/dashboard/project/phjgebfpybxcbfkxnckb/sql/new"
echo ""
echo "2. Copy the ENTIRE contents of this file:"
echo "   lib/supabase/storage.sql"
echo ""
echo "3. Paste into the SQL Editor"
echo ""
echo "4. Click 'Run' button"
echo ""
echo "5. You should see success messages for:"
echo "   - ALTER TABLE storage.objects"
echo "   - Multiple CREATE POLICY statements"
echo ""
echo "⚡ Quick Copy Command:"
echo "=========================================="
echo ""
echo "cat lib/supabase/storage.sql"
echo ""
echo "Then copy the output and paste into Supabase SQL Editor."
echo ""
echo "🧪 After Applying Policies:"
echo "=========================================="
echo ""
echo "1. Refresh your browser"
echo "2. Try uploading an audio file again"
echo "3. Should work without RLS errors"
echo ""
echo "✅ This is a ONE-TIME setup step."
echo ""
